# Generated by Django 2.0 on 2017-12-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieve', '0002_auto_20171218_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(),
        ),
    ]
