# Generated by Django 2.0 on 2017-12-18 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrieve', '0003_auto_20171218_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Books',
        ),
    ]
