# Generated by Django 2.0 on 2017-12-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrieve', '0004_auto_20171218_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
