# Generated by Django 2.0 on 2017-12-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieve', '0005_auto_20171218_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='-'),
        ),
    ]
