# Generated by Django 2.0 on 2017-12-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieve', '0006_auto_20171218_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('IDF', models.FloatField()),
                ('description', models.TextField(default='-')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='desc_wc',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_wc',
            field=models.TextField(default='-'),
        ),
    ]
