# Generated by Django 2.0 on 2017-12-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieve', '0007_auto_20171218_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='IDF',
        ),
        migrations.RemoveField(
            model_name='word',
            name='description',
        ),
        migrations.AddField(
            model_name='word',
            name='desc_idf',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='title_idf',
            field=models.FloatField(default=0),
        ),
    ]
